/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Garden__factory } from "./Garden__factory";
export { GardenProxy__factory } from "./GardenProxy__factory";
